### ISSUE TITLE
Make it a git alias

### ISSUE THREAD

**Issue by oliverpool** [no-gravity/git-retroamend#1]
Hi,

thank you very much for showing this!

I dug further and [found](https://stackoverflow.com/questions/1186535/how-to-modify-a-specified-commit#comment111009390_32850786) someone who made a git alias for excactly this (goes in ` ~/.gitconfig`):

```
fixup = "!fn() { git commit --fixup ${1} && GIT_EDITOR=true git rebase --autosquash -i ${1}^; }; fn"
```

(the `git add .` is absent, because I may want to control exactly what should be amended).

Usage: `git fixup <hash_of_an_old_commit>`

**Comment by oliverpool** [comment]
(I discovered your repo via lobste.rs, but I don't have an account there yet, to comment it)

**Comment by no-gravity** [comment]
Sure, that works too.
